### PR TITLE
fix(install): fix install on windows

### PR DESCRIPTION
**Pull request by dmccaffery**

### CODE REVIEW

**Review by keith9820 — APPROVED** [review]

**Comment by sjk07** [comment]
whats going on with this PR?

**Comment by dmccaffery** [comment]
@sjk07 It was a massive PR used to merge up changes required to support the new msbuild sdk, fixes to PowerShell, and a migration to using travis and appveyor for build once again.

**Comment by dmccaffery** [comment]
@sjk07 It was a massive PR used to merge up changes required to support the new msbuild sdk, fixes to PowerShell, and a migration to using travis and appveyor for build once again.

**Comment by sjk07** [comment]
@dmccaffery awesome stuff =]

**Pull request merged**
