### PR TITLE
docs: add docs

### PR DESCRIPTION
**Pull request by tiffanywang3**

### CODE REVIEW

**Comment by dmccaffery** [comment]
@sjk07

**Comment by sjk07** [comment]
@tiffanywang3 I think these are good for people who want to understand how condo works from a conceptual level. 

I think we are missing (not in priority order):
- Important condo flags
- How condo versions projects
- How condo creates a changelog from commit conventions.
- How condo pushes to package management
- How condo pushes to docker
- How to setup a CI pipeline with CircleCI, Appveyor, VSTS.
- How the condo.build file works and how to override / inject lifecycles.
- What condo is and what it isn't, what are the dependencies?

Just some ideas.

**Comment by sjk07** [comment]
@tiffanywang3 if you need more direction let me know. it might be a good idea to break some of these issues down and retire them. they are not very clear. just yell on the issues / ping me.

Really want to get 2.0 out so we can start having people use condo mainstream! 

We should also divide this work somehow. There is a lot to do for a single person

**Comment by frnek** [comment]
@tiffanywang3 Hi! I wanted to start working on it. Can we merge this PR into develop so I could work with what you already did?

**Comment by tiffanywang3** [comment]
Hi all, apologies for not addressing this sooner

**Pull request merged**
