### PR TITLE
Enable generation of symbols packages.

### PR DESCRIPTION
**Pull request by rstrugalski**

### CODE REVIEW

**Review by kacperj — APPROVED** [review]

**Comment by dmccaffery** [comment]
@sjk07 / @kacperj : is the azdo build still wired up? it seems to be hanged.

**Comment by kacperj** [comment]
> @sjk07 / @kacperj : is the azdo build still wired up? it seems to be hanged.

Thanks @dmccaffery, it was really issue with AM CI

**Comment by dmccaffery** [comment]
@kacperj : fixed the status check which started being reported differently (includes the name of the pipeline) -- looks ready to merge.

**Comment by agnauck** [comment]
looks like we should spend some to on moving it to GitHub or Azure pipelines to simplify ;-)

**Pull request merged**
