### PR TITLE
feat(docs): add support for github pages

### PR DESCRIPTION
**Pull request by dmccaffery**
* optin to publishing docs generated with docfx to github-pages
* automatically checkout and add a new commit to a github-pages branch or repository

### CODE REVIEW

**Comment by dmccaffery** [comment]
@sjk07 so the remaining issue here is the credentials for the push operation, right? They need to be copied under some circumstances.

**Comment by sjk07** [comment]
@dmccaffery I remember talking about getting a timeout for the push / credentials. Maybe at least a output in the console stating waiting for credentials... 

Also the potential that a CI server might get the auth from the local git-config instead of the user config (this might be pointless tho, since we dont know of any that do this).

**Comment by dmccaffery** [comment]
@sjk07 Not sure that I want to officially enable support for publishing docs to gh-pages from a developer machine -- it should be a CI-only scenario, but I do have to consider the fact that an authorization header / token might need to be set on the new clone of the repo.... The way that GH pages support works internally is as follows:

* Clone a copy of the repository to a temporary path on the file system
* Change to the gh-pages branch of the repository
* `git rm -rf *` everything in the branch
* copy the docs artifacts to the new clone
* `git add *` everything that was copied
* create a commit containing the docs
* push the commit to the repo (this is the part that may fail if machine-level credentials don't exist for the repository URI)

I think all that is missing is copying any authorization that was set locally be copied to the new clone to ensure that the push operation succeeds. I'll look at this again tonight.

**Comment by sjk07** [comment]
What's missing from this for it to be complete??

**Comment by dmccaffery** [comment]
@sjk07 this should now be good to go. I copy the authorization header if its available.

**Review by sjk07 — APPROVED** [review]

**Comment by dmccaffery** [comment]
@automotiveMastermind/masterminds as an fyi: this has not been merged yet due to the discovery of an additional dependency on the 2015 version of the msbuild tools imposed by docfx. I did get this working (as evidenced by: http://automotivemastermind.github.io/condo/api/), but I want to make sure that I handle missing dependencies appropriately (or emit a warning) -- docfx fails with a non descriptive error when the dependencies are missing.

**Pull request merged**
