### PR TITLE
build(azure): add azure pipeline and job spec

### PR DESCRIPTION
**Pull request by dmccaffery**
* add a job spec for azure-pipelines
* create a pipeline that will be used for continuous integration testing with Azure DevOps

### CODE REVIEW

**Comment by sjk07** [comment]
Can we see this work in azure??

Let's go!

**Comment by dmccaffery** [comment]
@sjk07; yes! that's the whole reason I added the root level "azure-pipeline.yaml" -- so we can run this build in our Azure DevOps instance as a check. :) We can also move the condo docker publish portion from CircleCI to Azure Pipelines as well (since we'll have an image cache and therefor much faster build). We will, of course, continue to run the CI target in CircleCI for build verification (just not the publish)... thats my thoughts, at least. :)

**Comment by dmccaffery** [comment]
I forced this through to test it out!

**Comment by sjk07** [comment]
Lol was hoping we could test it out without forcing it through but...

LETS GO!

**Pull request merged**
