### PR TITLE
docs(env): document AllowPublish for NuGet

### PR DESCRIPTION
**Pull request by agnauck**
documment that AllowPublish ENV variable controls Nuget push as well

### CODE REVIEW

**Review by sjk07 — APPROVED** [review]
LGTM

**Comment by agnauck** [comment]
CircleCI and AppVeyer are failing, should we worry about this?

**Comment by sjk07** [comment]
@agnauck we should probably remove CircleCI and AppVeyer; or add the missing framework dependencies they are complaining about

**Comment by dmccaffery** [comment]
I'd vote to move to GitHub Actions now that they are available.

**Pull request merged**
