### PR TITLE
fix: msbuildversion should be buildversion in csproj

### PR DESCRIPTION
**Pull request by sjk07**
I thought i did this in the last pr... i fail...

### CODE REVIEW

**Comment by sjk07** [comment]
@dmccaffery did this fail because i used a fork?

```
[00:02:21]      1>PrintDocFxProjects:
[00:02:21]          Project: am.condo, Root: True
[00:02:21]      1>C:\Users\appveyor\.am\condo\cli\Targets\Document\Dotnet.targets(48,5): error : The request was not successful. Forbidden - Forbidden [C:\projects\condo\condo.build]
[00:02:21]      1>Done Building Project "C:\projects\condo\condo.build" (ci;document target(s)) -- FAILED.
```

**Comment by dmccaffery** [comment]
Shouldn’t be; might be related to the token being wrong? I’ve used forks before successfully. Will look in a bit.

**Comment by dmccaffery** [comment]
That being said; I would force this PR through — this error is unrelated to the changes that were made.

**Review by dmccaffery — APPROVED** [review]

**Comment by sjk07** [comment]
will do. GOGOGO~

**Pull request merged**
